# Column mapping configuration for Brazilian polling stations data
# This file centralizes all column name mappings across different data sources
version: "1.0"
last_updated: "2025-01-06"
created_by: "Validation fix for issue #13"

# Global settings
global:
  standardize_case: "lowercase"  # Convert all column names to lowercase
  remove_accents: true          # Remove Portuguese accents from column names
  trim_whitespace: true         # Remove leading/trailing whitespace

# Data source specific mappings
data_sources:
  muni_identifiers:
    source_file_pattern: "muni_identifiers.csv"
    description: "Municipality identifier mappings from various Brazilian agencies"
    column_mappings:
      # Map various municipality code formats to standard names
      "Cod_Mun": "id_TSE"           # TSE uses this for municipality codes
      "cod_mun": "id_TSE"
      "codigo_municipio": "id_munic_7"
      "cod_municipio": "id_munic_7"
    required_columns: ["id_munic_7", "id_munic_6", "estado_abrev", "municipio"]
    optional_columns: ["id_TSE", "id_RF", "id_BCB", "id_comarca"]
    
  inep_codes:
    source_file_pattern: "inep_codes.csv"
    description: "INEP school codes - simplified format with just code and municipality"
    column_mappings:
      "co_entidade": "codigo_inep"
      "CO_ENTIDADE": "codigo_inep"
      "co_municipio": "id_munic_7"
      "CO_MUNICIPIO": "id_munic_7"
    required_columns: ["codigo_inep", "id_munic_7"]
    # Note: This file doesn't contain school names or coordinates
    
  inep_catalog:
    source_file_pattern: "inep_catalogo_das_escolas"
    description: "Full INEP school catalog with details and coordinates"
    column_mappings:
      # Portuguese to standardized names
      "Código INEP": "codigo_inep"
      "codigo inep": "codigo_inep"
      "Escola": "nome_escola"
      "escola": "nome_escola"
      "Município": "nome_municipio"
      "municipio": "nome_municipio"
      "UF": "uf"
      "Endereço": "endereco"
      "endereco": "endereco"
      "Latitude": "latitude"
      "latitude": "latitude"
      "Longitude": "longitude"
      "longitude": "longitude"
      "Localização": "localizacao"
      "Dependência Administrativa": "dependencia_admin"
      "Telefone": "telefone"
      # Alternative names from older versions
      "CO_ENTIDADE": "codigo_inep"
      "NO_ENTIDADE": "nome_escola"
      "co_entidade": "codigo_inep"
      "no_entidade": "nome_escola"
      "NU_LATITUDE": "latitude"
      "NU_LONGITUDE": "longitude"
      "nu_latitude": "latitude"
      "nu_longitude": "longitude"
    required_columns: ["codigo_inep"]
    optional_columns: ["nome_escola", "latitude", "longitude", "endereco", "uf", "nome_municipio"]
    
  locais_votacao:
    source_file_pattern: "eleitorado_local_votacao"
    description: "TSE voting location data"
    column_mappings:
      # Map uppercase TSE columns to lowercase standard
      "NM_LOCVOT": "nome_local"
      "NM_LOCALIDADE": "nome_localidade"
      "nm_local": "nome_local"
      "nm_muni": "nome_municipio"
      "CD_LOCALIDADE": "cod_localidade"
      "cd_localidade": "cod_localidade"
      "NR_LATITUDE": "latitude"
      "nr_latitude": "latitude"
      "NR_LONGITUDE": "longitude" 
      "nr_longitude": "longitude"
      "DS_ENDERECO": "endereco"
      "ds_endereco": "endereco"
      "NM_BAIRRO": "bairro"
      "nm_bairro": "bairro"
      "NR_CEP": "cep"
      "nr_cep": "cep"
    required_columns: ["nome_local", "cod_localidade"]
    optional_columns: ["latitude", "longitude", "endereco", "bairro", "cep"]
    
  cnefe_2010:
    source_file_pattern: "cnefe_2010|CNEFE.*2010"
    description: "2010 Census address data (CNEFE)"
    column_mappings:
      "cod_municipio": "id_munic_7"
      "nome_do_logradouro": "logradouro"
      "titulo_do_logradouro": "tipo_logradouro"
      "numero": "numero"
      "latitude": "latitude"
      "longitude": "longitude"
    transformations:
      - type: "lowercase_all"
      - type: "remove_accents"
        
  cnefe_2022:
    source_file_pattern: "cnefe_2022|cnefe22"
    description: "2022 Census address data (CNEFE)"
    column_mappings:
      "COD_MUNICIPIO": "id_munic_7"
      "cod_municipio": "id_munic_7"
      "NOM_TITULO_SEGLOGR": "tipo_logradouro"
      "nom_titulo_seglogr": "tipo_logradouro"
      "NOM_SEGLOGR": "logradouro"
      "nom_seglogr": "logradouro"
      "NUM_ENDERECO": "numero"
      "num_endereco": "numero"
    transformations:
      - type: "lowercase_all"

# Validation rules with flexible column checking
validation_rules:
  muni_ids:
    expected_columns: ["id_munic_7", "id_munic_6", "estado_abrev", "municipio"]
    column_alternatives:
      id_TSE: ["id_TSE", "Cod_Mun", "cod_mun"]
      id_munic_7: ["id_munic_7", "codigo_municipio", "cod_municipio"]
      
  inep_codes:
    expected_columns: ["codigo_inep", "id_munic_7"]
    column_alternatives:
      codigo_inep: ["codigo_inep", "co_entidade", "CO_ENTIDADE", "Código INEP"]
      id_munic_7: ["id_munic_7", "co_municipio", "CO_MUNICIPIO"]
      
  inep_cleaned:
    expected_columns: ["codigo_inep", "latitude", "longitude"]
    column_alternatives:
      latitude: ["latitude", "lat", "Latitude", "NU_LATITUDE"]
      longitude: ["longitude", "lon", "long", "Longitude", "NU_LONGITUDE"]
      
  locais:
    expected_columns: ["nome_local", "cod_localidade"]
    column_alternatives:
      nome_local: ["nome_local", "nm_local", "NM_LOCVOT"]
      nome_municipio: ["nome_municipio", "nm_muni", "NM_LOCALIDADE"]

# Known exceptions and edge cases
exceptions:
  # Special municipality codes that don't follow standard patterns
  special_municipalities:
    - name: "Fernando de Noronha"
      id_munic_7: "2605459"
      note: "Island territory with special administrative status"
    - name: "Brasília"
      id_munic_7: "5300108"
      note: "Federal District"
      
  # INEP codes that may have non-standard formats
  inep_format_exceptions:
    - pattern: "^[A-Z]{2}[0-9]{6}$"
      description: "State prefix format (e.g., SP123456)"
      action: "extract_numeric"